run:
  deadline: 10m

linters:
  enable:
    - contextcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
