run:
  deadline: 10m

linters:
  enable:
    - contextcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert

issues:
  exclude-rules:
  # Exclude the gocritic dupSubExpr issue for cgo files.
  - path: internal/dxcore/dxcore.go
    linters:
    - gocritic
    text: dupSubExpr
